---
playbook_debug: no
namespace: "{{ lookup('env','NAMESPACE') | default('wordpress-ha', true) }}"
root_password: "{{ lookup('env','ROOT_PASSWORD') | default('k8spassword', true) }}"
xtrabackup_password: "{{ lookup('env','XTRABACKUP_PASSWORD') | default('k8spassword', true) }}"
cluster_name: "{{ lookup('env','CLUSTER_NAME') | default('percona', true) }}"
database_password: "{{ lookup('env','DATABASE_PASSWORD') | default('k8spassword', true) }}"
database_user: "{{ lookup('env','DATABASE_USER') | default('root', true) }}"
database_host: "{{ lookup('env','DATABASE_HOST') | default('mysql', true) }}"
discovery_service: "{{ lookup('env','DISCOVERY_SERVICE') | default('etcd:2379', true) }}"
state: present
